wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1708884901.830083
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.13.2
      8:
      - 4
      - 5
alpha:
  desc: null
  value: 0.2
backend:
  desc: null
  value: MPI
batch_size:
  desc: null
  value: 64
client_id_list:
  desc: null
  value: '[]'
client_num_in_total:
  desc: null
  value: 10
client_num_per_round:
  desc: null
  value: 10
client_optimizer:
  desc: null
  value: AdamW
comm:
  desc: null
  value: <mpi4py.MPI.Intracomm object at 0x2880686f0>
comm_round:
  desc: null
  value: 100
data_cache_dir:
  desc: null
  value: ./ego-networks/
dataset:
  desc: null
  value: citeseer
dropout:
  desc: null
  value: 0.3
ego_number:
  desc: null
  value: 1000
enable_wandb:
  desc: null
  value: true
epochs:
  desc: null
  value: 5
federated_optimizer:
  desc: null
  value: FedAvg
frequency_of_the_test:
  desc: null
  value: 5
gpu_mapping_file:
  desc: null
  value: config_fedavg/gpu_mapping.yaml
gpu_mapping_key:
  desc: null
  value: mapping_config3_11
graph_embedding_dim:
  desc: null
  value: 64
hidden_size:
  desc: null
  value: 32
hop_number:
  desc: null
  value: 5
is_mobile:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.001
local_rank:
  desc: null
  value: 0
log_file_dir:
  desc: null
  value: ./log
metric:
  desc: null
  value: prc-auc
model:
  desc: null
  value: gcn
n_layers:
  desc: null
  value: 5
node_embedding_dim:
  desc: null
  value: 32
node_rank:
  desc: null
  value: 0
normalize_adjacency:
  desc: null
  value: false
normalize_features:
  desc: null
  value: false
num_heads:
  desc: null
  value: 2
part_file:
  desc: null
  value: ./ego-networks/citeseer/partition
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
process_id:
  desc: null
  value: 4
random_seed:
  desc: null
  value: 0
rank:
  desc: null
  value: 4
readout_hidden_dim:
  desc: null
  value: 64
role:
  desc: null
  value: client
run_device_id:
  desc: null
  value: '0'
run_id:
  desc: null
  value: '0'
run_name:
  desc: null
  value: citeceer_origin
sparse_adjacency:
  desc: null
  value: false
sys_perf_profiling:
  desc: null
  value: true
training_type:
  desc: null
  value: simulation
using_gpu:
  desc: null
  value: true
using_mlops:
  desc: null
  value: false
wandb_project:
  desc: null
  value: fedml
weight_decay:
  desc: null
  value: 0.001
worker_num:
  desc: null
  value: 11
yaml_config_file:
  desc: null
  value: config_fedavg/simulation_gcn/fedml_config.yaml
yaml_paths:
  desc: null
  value:
  - config_fedavg/simulation_gcn/fedml_config.yaml
