common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "clintox"
  data_cache_dir: ~/fedgraphnn_data/
  partition_method: "homo"
  partition_alpha: 0.5

model_args:
  model: "gcn"
  hidden_size: 32
  node_embedding_dim: 32
  graph_embedding_dim: 64
  readout_hidden_dim: 64
  alpha: 0.2
  num_heads: 2
  dropout: 0.5
  normalize_features: False
  normalize_adjacency: False
  sparse_adjacency: False

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 4
  client_num_per_round: 4
  comm_round: 100
  epochs: 5
  batch_size: 64
  client_optimizer: adam
  learning_rate: 0.0015
  weight_decay: 0.001
  metric: "roc-auc"

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: false
  gpu_mapping_file: config_fedavg/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: True
  #wandb_key: 571c2b7011299438adab08485020f3ecbfcb8af0
  wandb_project: clintox
  run_name: fed_gcn