wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1709369145.946107
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 2
      - 13
      - 23
      4: 3.8.18
      5: 0.13.2
      8:
      - 4
      - 5
